spring:
  redis:
    port: 6379
    host: localhost

  cloud:
    gateway:
      routes:
        - id: api-interface
          uri: lb://api-interface
          predicates:
            - Path=/api/**
          filters:
            - name: RequestRateLimiter
              args:
                # 令牌桶每秒填充平均速率, 允许用户每秒处理多少个请求。
                redis-rate-limiter.replenishRate: 1
                # 令牌桶的容量，允许在1s内完成的最大请求数。
                redis-rate-limiter.burstCapacity: 1
                # 使用SpEL表达式从Spring容器中获取Bean对象, 查看RateLimiteConfig实现类中的方法名
                key-resolver: "#{@pathKeyResolver}"
                #key-resolver: "#{@ipKeyResolver}"
                #key-resolver: "#{@userKeyResolver}"
dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: 20880
  registry:
    # address: spring-cloud://localhost #挂载到springcloud注册中心
    address: localhost:8848
  consumer:
    check: false #dubbo默认有启动检查
    retries: 0 #dubbo内置的重试机制