spring:
  redis:
    port: 6379
    host: host.docker.internal
    password:
  cloud:
    gateway:
      routes:
        - id: api-interface
          uri: http://host.docker.internal:8123
          predicates:
            - Path=/api/**
dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://host.docker.internal:8848